Vastly Improve auto-bspwmrc
- Add support for using display edid to determine mode
	- Really useful for displays where the preferred mode may not be
	  available. (And X defaults to something stupid)
	  e.g. Using a 1440p144hz display with HDMI 1.4
- Add "DEBUG" output mode, and default to cleaner output
- Refactor gross nested loops
- Refactor many variable names
- Fix multitude of outstanding edgecase bugs

diff --git a/dot-config/bspwm/bspwmrc b/dot-config/bspwm/bspwmrc
--- a/dot-config/bspwm/bspwmrc
+++ b/dot-config/bspwm/bspwmrc
@@ -1,67 +1,83 @@
 #! /bin/bash
 #
-# Automatically configures displays based on a simple config array.
-# Absolutely cursed, but working...
+# auto-bspwmrc: Dynamic BSPWM display configuration.
+#
+# Luna Hart <luna@night.horse>
 
 # shellcheck disable=SC1090
 source ~/.profile
 export PATH=$HOME/.cargo/env:$PATH
 
-set -x
+REDIRECT="/dev/null"
+if [[ -n "$DEBUG" || -n "$VERBOSE" ]]; then
+	set -x
+	REDIRECT="/dev/stdout"
+fi
 
-# hint as to what the primary monitor should be. Else random selection.
-DP_HINT_PRIMARY=("DP-2-3")
+# Array of primary monitors. First match will be used.
+X_PRIMARY=("DP-2-3")
 
-# strings that order monitors from left to right
-# order in priority of config
-# specify orientation (none, left, right, inverted)
-DP_HINT_ORDERED_CONFIGS=("eDP-1 normal DP-4 normal" "eDP-1 normal DP-2-3 normal DP-2-2 normal" "eDP-1 normal DP-2-3 normal")
-DH_CFG_PARAM_COUNT=2
+# Array of monitor order configs.
+# string format: "[MONITOR1_OUTPUT] [MONITOR1_ORIENTATION] [MONITOR2_OUTPUT] [MONITOR2_ORIENTATION] ..."
+X_ORDERED_CONFIGS=("eDP-1 normal DP-2-3 normal DP-2-1 normal" "eDP-1 normal DP-2-3 normal" "eDP-1 normal DP-2 normal")
+XOC_PARAM_COUNT=2
 
+# Array of edid modeline config strings.
+# string format: "[EDID_MODEL] [XRANDR_MODELINE]"
+EDID_MODE_CONFIG=("27GL850 2560x1440")
+
+# Total desktops used by BSPWM
 BSPWM_DESKTOP_COUNT=13
-BSPWM_SDS=80
+# Percentage (vs equal split) of desktops that will be given to primary monitor.
+BSPWM_PRIMARY_DESKTOP_BIAS=120
 
-function get_mon_index {
-	for i in "${!con_mon[@]}"; do
-	if [[ "${con_mon[$i]}" = "${1}" ]]; then
-		echo "${i}"
-	fi
-	done
+function get_monitor_model_by_edid {
+	local edid_path
+	# XXX(luna) We should consider multiple "card" systems. Maybe a search.
+	edid_path="/sys/class/drm/card0-${1}/edid"
+	test -f "$edid_path" || return 1
+	parse-edid < "${edid_path}" 2> /dev/null | grep ModelName | sed 's/.*"\(.*\)"/\1/'
+	return 0
 }
 
-function enumerate_displays {
+function try_edid_config {
+	local output="$1"
 	local config
-	local config_displays
-	local output
-	local orientation
-	local prev_output
-	local max_res_in_cfg
-	local h_con_mon
-	local cur_dim
-	local xpos
-	local ypos
-	local mon_index
-	xpos=0
-	ypos=0
-
-	# populated "connected displays"
-	mapfile -t connected_displays < <(xrandr --query | awk '/ connected /{print$1}')
-
-	con_mon=( "${connected_displays[@]}" )
-	# w_con_mon=( $(xrandr | grep "   .*+" | sed -E "s/   ([0-9]*)x([0-9]*).*/\1/") )
-	mapfile -t h_con_mon < <(xrandr | grep "   .*+" | sed -E "s/   ([0-9]*)x([0-9]*).*/\2/")
-	IFS=$'\n'
-	max_res_in_cfg="$(echo "${h_con_mon[*]}" | sort -nr | head -n1)"
-	unset IFS
-
-	# check configs for a matching one
-	for config in "${DP_HINT_ORDERED_CONFIGS[@]}"; do
-		echo "$config"
+	local model
+	model="$(get_monitor_model_by_edid "$output" || return $?)"
+	for config in "${EDID_MODE_CONFIG[@]}"; do
 		IFS=" " read -r -a config <<< "$config"
+		if [[ "${config[0]}" = "${model}" ]]; then
+			echo "Matched edid profile for: $model($output)"
+			xrandr --output "$output" --mode "${config[1]}"
+			return $?
+		fi
+	done
+	return 0
+}
+
+function get_display_idx {
+	for i in "${!connected_displays[@]}"; do
+		if [[ "${connected_displays[$i]}" = "${1}" ]]; then
+			echo "${i}"
+			return
+		fi
+	done
+	return 1
+}
+
+# populates: "$target_displays"
+# populates: "$config"
+function try_match_display_config {
+	local config_raw
+	local config_displays
+	# check configs for a matching one
+	for config_raw in "${X_ORDERED_CONFIGS[@]}"; do
+		IFS=" " read -r -a config <<< "$config_raw"
 
 		# check if config matches current displays
 		config_displays=()
-		for ((i=0; i<${#config[@]}; i+=DH_CFG_PARAM_COUNT)); do
+		for ((i=0; i<${#config[@]}; i+=XOC_PARAM_COUNT)); do
 			# add to list of config's displays
 			config_displays+=("${config[i]}")
 			# check if display not in connected array
@@ -70,63 +86,102 @@ function enumerate_displays {
 					continue 2
 				fi
 			done
-			echo "Config no match"
 			continue 2
 		done
 
-		# apply config if match made
-		echo -e "\\tmatch!"
-		# apply monitor order/orientation
-		for ((i=0; i<${#config[@]}; i+=DH_CFG_PARAM_COUNT)); do
-			output="${config[i]}"
-			orientation="${config[i+1]}"
-			mon_index="$(get_mon_index "$output")"
-			echo "$mon_index"
-			xpos=0
-			ypos=$(( max_res_in_cfg - h_con_mon[mon_index] ))
-			# set display position if needed
-			if ((i > 0)); then
-				cur_dim="$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')"
-				xpos=$(echo "$cur_dim" | sed -E 's/(.*)x.*/\1/')
-				prev_output="${config[i-DH_CFG_PARAM_COUNT]}"
-				xrandr --output "$output" \
-					--right-of "$prev_output"
-			fi
-			# set orientation of display
-			xrandr --output "$output" \
-				--rotate "$orientation"
-		done
+		target_displays=("${config_displays[@]}")
+		echo "Using config: $config_raw"
+		return 0
 
-		# apply fine monitor position
-		for ((i=0; i<${#config[@]}; i+=DH_CFG_PARAM_COUNT)); do
-			output="${config[i]}"
-			mon_index="$(get_mon_index "$output")"
-			xpos=$(xrandr | grep "$output" | sed -E "s/.*\+([0-9]*)\+.*/\1/")
-			ypos=$(( max_res_in_cfg - h_con_mon[mon_index] ))
-			# asserts all displays are aligned at bottom
-			xrandr --output "$output" \
-				--pos "${xpos}x${ypos}"
-		done
-		connected_displays=("${config_displays[@]}")
-		echo "config applied!"
-		return
 	done
 
-	# attempt failover, no config applied
-	echo "I see no friendly monitors... This is scary... *sniff*"
-	echo "Must.. Continue.. Using the first output I saw!"
-	connected_displays=("${connected_displays[0]}")
-	return
+	# attempt failover, no config found
+	>&2 echo "I see no friendly monitors... This is scary... *sniff*" 
+	>&2 echo "Must.. Continue.. Using the first output I saw!"
+	target_displays=("${connected_displays[0]}")
+	echo "${connected_displays[0]} normal"
+	return 0
 }
 
-# expects bash array as "connected_displays" and DP_HINT_PRIMARY
+function enumerate_displays {
+	local config
+	local config_displays
+	local output
+	local orientation
+	local prev_output
+	# vertical heights of displays by global idx
+	local h_displays
+	local max_h_displays
+	local cur_dim
+	local xpos
+	local ypos
+	local display_idx
+	xpos=0
+	ypos=0
+
+
+	# populated "connected displays"
+	mapfile -t connected_displays < <(xrandr --query | awk '/ connected /{print$1}')
+	#con_mon=( "${connected_displays[@]}" )
+	# initialize modes of connected displays based on edid
+	for output in "${connected_displays[@]}"; do
+		try_edid_config "${output}"
+	done
+
+	# populate connected display vertical height data
+	# XXX(luna) think we might want to limit `max_h_displays` to those in config?
+	mapfile -t h_displays < <(xrandr | grep "   .*\*" | sed -E "s/   ([0-9]*)x([0-9]*).*/\2/")
+	IFS=$'\n'
+	max_h_displays="$(echo "${h_displays[*]}" | sort -nr | head -n1)"
+	unset IFS
+
+	# get display config
+	try_match_display_config
+
+	# apply monitor order/orientation
+	for ((i=0; i<${#config[@]}; i+=XOC_PARAM_COUNT)); do
+		output="${config[i]}"
+		orientation="${config[i+1]}"
+		display_idx="$(get_display_idx "$output")"
+		xpos=0
+		ypos=$(( max_h_displays - h_displays[display_idx] ))
+		# set display order if needed
+		if ((i > 0)); then
+			cur_dim="$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')"
+			xpos=$(echo "$cur_dim" | sed -E 's/(.*)x.*/\1/')
+			prev_output="${config[i-XOC_PARAM_COUNT]}"
+			xrandr --output "$output" \
+				--right-of "$prev_output"
+		fi
+		# set orientation of display
+		xrandr --output "$output" \
+			--rotate "$orientation"
+	done
+
+	# apply fine monitor position
+	# 1. all displays are aligned at bottom (BSPWM bugs out otherwise)
+	# 2. all displays are aligned alongside each other.
+	for ((i=0; i<${#config[@]}; i+=XOC_PARAM_COUNT)); do
+		output="${config[i]}"
+		display_idx="$(get_display_idx "$output")"
+		xpos=$(xrandr | grep "$output" | sed -E "s/.*\+([0-9]*)\+.*/\1/")
+		ypos=$(( max_h_displays - h_displays[display_idx] ))
+		xrandr --output "$output" \
+			--pos "${xpos}x${ypos}"
+	done
+	
+	return 0
+}
+
+# consumes: "$target_displays"
+#           "$DP_HINT_PRIMARY"
 function configure_bspwm_desktops {
 	local primary
 	local desktop_count
 
 	# determine if we have a primary monitor attached
-	for primary in "${DP_HINT_PRIMARY[@]}"; do
-		for i_display in "${connected_displays[@]}"; do
+	for primary in "${X_PRIMARY[@]}"; do
+		for i_display in "${target_displays[@]}"; do
 			if [[ "${i_display}" = "$primary" ]]; then
 				break 2
 			fi
@@ -137,17 +192,17 @@ function configure_bspwm_desktops {
 	# calculate desktop counts
 	if [[ -z "$primary" ]]; then
 		primary_desktop_count=0
-		secondary_desktop_count=$((BSPWM_DESKTOP_COUNT/${#connected_displays[@]}))
+		secondary_desktop_count=$((BSPWM_DESKTOP_COUNT/${#target_displays[@]}))
 	else
-		secondary_desktop_count=$(( ( (BSPWM_DESKTOP_COUNT * BSPWM_SDS) / 100)\
-			/${#connected_displays[@]}))
-		primary_desktop_count=$((BSPWM_DESKTOP_COUNT - \
-			secondary_desktop_count * (${#connected_displays[@]} - 1)))
+		secondary_desktop_count=$(( ( (BSPWM_DESKTOP_COUNT / ${#target_displays[@]}) \
+			* 100) / BSPWM_PRIMARY_DESKTOP_BIAS ))
+		primary_desktop_count=$((BSPWM_DESKTOP_COUNT \
+			- secondary_desktop_count * (${#target_displays[@]} - 1)))
 	fi
 	desktop_count=1
 
 	# add desktops and configure for displays
-	for display in "${connected_displays[@]}"; do
+	for display in "${target_displays[@]}"; do
 		if [[ "$display" = "$primary" ]]; then
 			next_desktop_count=$((desktop_count + primary_desktop_count))
 		else
@@ -156,10 +211,8 @@ function configure_bspwm_desktops {
 		bspc monitor "$display" -d $(seq --separator=" " \
 			"$desktop_count" "$((next_desktop_count - 1))")
 		export MONITOR="$display"
-		if [[ "$display" = "$primary" || $((${#connected_displays[@]} == 1)) ]]; then
-			polybar bottomright &
-		fi
-		polybar bottomleft &
+		polybar bottomright &> "$REDIRECT" &
+		polybar bottomleft &> "$REDIRECT" &
 		desktop_count="$next_desktop_count"
 	done
 }
@@ -214,15 +267,15 @@ export _JAVA_AWT_WM_NONREPARENTING=1
 
 # fork/start useful things
 #   network manager systray util
-nm-applet &
+nm-applet > "$REDIRECT" &
 #   hotkey daemon
-sxhkd &
+sxhkd > "$REDIRECT" &
 #   Java compatible wmname
-wmname LG3D &
+wmname LG3D > "$REDIRECT" &
 #   wallpaper
-feh --bg-fill ~/.config/wallpapers/background.png &
+feh --bg-fill ~/.config/wallpapers/background.png > "$REDIRECT" &
 #   compositor
-picom --experimental-backends --blur-method dual_kawase &
+picom --experimental-backends --blur-method dual_kawase > "$REDIRECT" &
 
 # configure xinput stuff
 #   root cursor
@@ -231,4 +284,6 @@ xsetroot -cursor_name left_ptr
 xmodmap -e "keycode 166 = Prior"
 xmodmap -e "keycode 167 = Next"
 
-set +x
+if [[ -n "$DEBUG" || -n "$VERBOSE" ]]; then
+	set +x
+fi
